api_platform:
    title: CRM API
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    formats:
        json:
            mime_types:
                - application/json
        jsonld:
            mime_types:
                - application/ld+json
    patch_formats:
        json:
            mime_types:
                - application/merge-patch+json
